name: CI
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: curl -L https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz | tar -xzvf -
    - run: make -s push-release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
